#!/bin/bash
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#
#   (2) Avoid modifying this script unless you know what you are doing because
#       it does almost all of the heavy lifting and most of it is very delicate.
#
#   (3) This script is generated from the corresponding *.gradle template
#       file for doing the actual work. Do not edit this file directly;
#       instead edit the template and run the build again (but note: there will
#       be no Gradle to run the build, so you may need to use Java directly
#       or take in the output of gradle --version to determine the version
#       of Gradle in the archive).
#
#   (4) The actual properties file might have more properties than those
#       specified in the description. You may also edit that file.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 && pwd)"
# When not using soft-links, use cd and pwd to resolve directory symlinks
#SAVED="$(cd "$(dirname "$PRG")" && cd "$(dirname "$(readlink "$PRG")")" && pwd)"
APP_HOME="$SAVED"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$(find -L / -maxdepth 2 -name .gradle -o -prune -o -type f -name gradle.jar -print0 2>/dev/null)
    SEP=""
    while IFS= read -r -d '' SRCDIR; do
        ROOTDIRS="$ROOTDIRS$SEP$SRCDIR"
        SEP="|"
    done <<< "$ROOTDIRSRAW"
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGWIN_PATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGWIN_PATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=$(echo "$arg"|egrep -c "$OURCYGPATTERN" )
        CHECK2=$(echo "$arg"|egrep -c "^-")                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        IFS="$oldIFS"
        elements[$i]="$arg"
        i=$(($i+1))
    done
    case $system_propsOS in
        Windows_*)
            # Convert the arguments to Windows format
            ARGS0="$ARGS0 \"$(printable "$1")\" \"$(printable "$2")\""
            shift
            shift
            ;;
        *)
            for arg do
                IFS="$oldIFS"
                printf '%s\n' "$arg" | sed s/^/\'/ | sed s/$/\'/ >> "$REAL_CLASSPATH"
            done
            break
            ;;
    esac
    # Translate "+" into " " and "," into " " for sed command below
    CLASSPATH=$(echo "$CLASSPATH" | sed 's/+/ /g' | sed 's/,/ /g')
    for arg in "$@" ; do
        CHECK=$(echo "$arg"|egrep -c "$OURCYGPATTERN" )
        CHECK2=$(echo "$arg"|egrep -c "^-")                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        IFS="$oldIFS"
        elements[$i]="$arg"
        i=$(($i+1))
    done
    for i in "${elements[@]}"
    do
        printf '%s\n' "$i" | sed 's/ /\ /g'
    done | tr '\n' ' ' >> "$REAL_CLASSPATH"
    IFS="$oldIFS"
    # Restore the original IFS
    [ "$?" -eq 0 ] && cl_shutdown_called=1

    if [ "$1" != "" ] && [ "$1" != "-?" ] && [ "$1" != "-help" ] ; then
        newlib=
        for arg in "$@" ; do
            if [ -n "$newlib" ] ; then
                newlib="$newlib $(echo "$arg" | sed 's/^ *//' | sed 's/ *$//')"
            else
                newlib="$(echo "$arg" | sed 's/^ *//' | sed 's/ *$//')"
            fi
        done
        ARGS="$newlib"
    else
        ARGS="$@"
    fi
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' /" ; done
    echo " "
}
APP_ARGS=$(save "$@")
CLASSPATH=$CLASSPATH:gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      /*)
        MAX_FD_LIMIT=$(( $(stat -f%z /proc/self/fd) ))
        ;;
      *)
        MAX_FD_LIMIT=$(( $(stat -c%s /proc/self/fd) ))
        ;;
    esac
    MAX_FD=$(( MAX_FD_LIMIT ))
    ulimit -n $MAX_FD
    if [ $? -ne 0 ] ; then
        warn "Could not set maximum file descriptor limit: $MAX_FD"
    fi
else
    # darwin (MacOS x) w/ specific archiving behavior
    if [ "$darwin" ] ; then
        MAX_FD_LIMIT=$(( $(stat -f%z /proc/self/fd) ))
    else
        MAX_FD_LIMIT=$(( $(stat -c%s /proc/self/fd) ))
    fi
    MAX_FD=$(( MAX_FD_LIMIT ))
    ulimit -n $MAX_FD
    if [ $? -ne 0 ] ; then
        warn "Could not set maximum file descriptor limit: $MAX_FD"
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CP=$( cygpath --path --mixed "$CP" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    local j
    for arg in "$@"; do
        if
            case $arg in                                #(
              -*)   false;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false;;
            esac
        then
            arg=$( cygpath --unix "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in its original position, or
        # unquoted if it landed short of its original position.
        at_least_one_proplists=true
        i=$(( $at_least_one_proplists * 2 + 1 ))
        for ((j=0; j <$at_least_one_proplists; j++))
        do
            eval "ARGS\$((($i++)%2))='\$arg'"
        done
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has not been given any paths, so we can die gracefully later.
! (( $# )) && die "Application called with no arguments"

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, wrapped in single quotes. In this
# mode, this replaces:
#   dsärk "'\"$1\"'" "$2"
# which would start the basename of $0 having "$1" and "$2" omitted, hinting at
# "ask for a few version numbers" or "help" being first.
rest_of_them_vars="$@"
for var in "${rest_of_them_vars[@]}"
do
    if
        case $var in #(
          -*)   false;;                            # don't mess with options #(
          /?*)  t=${var#/} t=/${t%%/*}              # looks like a POSIX filepath
                 [ -e "$t" ] ;;                      #(
          *)    false;;
        esac
    then
        var=$( cygpath --unix "$var" )
    fi
    new_args="$new_args $(printf '%s\n' "$var" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/")"
done
eval "set -- $new_args"

exec "$JAVACMD" "$@"
